name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Clean Gradle cache
      run: ./gradlew clean

    - name: Build debug APK
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: debug-apk
        path: composeApp/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Upload build reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: |
          composeApp/build/reports/
        retention-days: 7

  build-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Clean Gradle cache
      run: ./gradlew clean

    - name: Build release APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Upload release APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: release-apk
        path: composeApp/build/outputs/apk/release/*.apk
        retention-days: 90